FLP-622-PricesUpdatedInCommitments
SkillsFundingAgency/das-apprenticeships pull request #107
Opened 2024-09-17 12:55 UTC by MikeV-TalentConsulting

2024-09-17 15:58 UTC, tom-gough requested changes

2024-09-17 15:58 UTC, tom-gough commented on src/Domain.Tests/Apprenticeship/Events/WhenHandlePriceChangeApproved.cs
> +    private static bool SendsApproverAndInittorDetails(ApprenticeshipPriceChangedEvent e, PriceHistoryDomainModel priceChange)
Is this a typo?

2024-09-18 08:09 UTC, MikeV-TalentConsulting commented on src/Domain.Tests/Apprenticeship/Events/WhenHandlePriceChangeApproved.cs
> +    private static bool SendsApproverAndInittorDetails(ApprenticeshipPriceChangedEvent e, PriceHistoryDomainModel priceChange)
Lol, yes, good spot

2024-09-18 08:25 UTC, tom-gough approved these changes

2024-10-01 10:50 UTC, merged